name: T00thTransaction
main: t00thpick1.T00thTransaction
version: 1.5
author: t00thpick1
depend: [Vault]
commands:
   ttr:
      Description: Does everything
   giftbox:
      Description: List available gifts
   gift:
      Description: Activate gift
   package:
      Description: Activate package
   packages:
      Description: List available packages

permissions:
    t00thtransaction.admin:
        description: Ability to use everything
        default: false
    t00thtransaction.check:
        description: Ability to check others balances
        default: false